## Educational Analytics Platform

### Data Ingestion

\Importing Necessary libraries

In [22]:
import numpy as np
import pandas as pd
import os

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns",None)
pd.set_option("display.width",1000)

\Loading the dataset

In [39]:
def load_dataset(file_path):
    try:
        df=pd.read_csv(file_path)
        print(f"Dataset loaded successfully")
        print(f"Shape: {df.shape[0]} rows * {df.shape[1]} columns")
        return df
    except FileNotFoundError:
        print(f"error: File Not Found")
        return None
    except pd.errors.EmptyDataError:
        print(f"error: File is Empty")
        return None
    except Exception as e:
        print(f"error: {e}")
        return None

In [40]:
placement_df=load_dataset(r"C:\NG\Educational-Analytics-Platform\data\raw\placementdata.csv")
course_df=load_dataset(r"C:\NG\Educational-Analytics-Platform\data\raw\online_course_engagement_data.csv")
dropout_df=load_dataset(r"C:\NG\Educational-Analytics-Platform\data\raw\student_dropout_dataset.csv")

Dataset loaded successfully
Shape: 10000 rows * 12 columns
Dataset loaded successfully
Shape: 9000 rows * 9 columns
Dataset loaded successfully
Shape: 10000 rows * 19 columns

\data preview

In [25]:
placement_df.head()

   StudentID  CGPA  Internships  Projects  Workshops/Certifications  AptitudeTestScore  SoftSkillsRating ExtracurricularActivities PlacementTraining  SSC_Marks  HSC_Marks PlacementStatus
0          1   7.5            1         1                         1                 65               4.4                        No                No         61         79       NotPlaced
1          2   8.9            0         3                         2                 90               4.0                       Yes               Yes         78         82          Placed
2          3   7.3            1         2                         2                 82               4.8                       Yes                No         79         80       NotPlaced
3          4   7.5            1         1                         2                 85               4.4                       Yes               Yes         81         80          Placed
4          5   8.3            1         2                         2                 86               4.5                       Yes               Yes         74         88          Placed

In [28]:
course_df.head()

   UserID CourseCategory  TimeSpentOnCourse  NumberOfVideosWatched  NumberOfQuizzesTaken  QuizScores  CompletionRate  DeviceType  CourseCompletion
0    5618         Health          29.979719                     17                     3   50.365656       20.860773           1                 0
1    4326           Arts          27.802640                      1                     5   62.615970       65.632415           1                 0
2    5849           Arts          86.820485                     14                     2   78.458962       63.812007           1                 1
3    4992        Science          35.038427                     17                    10   59.198853       95.433162           0                 1
4    3866    Programming          92.490647                     16                     0   98.428285       18.102478           0                 0

In [31]:
dropout_df.head()

   Student_ID   Age  Gender  Family_Income Internet_Access  Study_Hours_per_Day  Attendance_Rate  Assignment_Delay_Days  Travel_Time_Minutes Part_Time_Job Scholarship  Stress_Index   GPA  Semester_GPA  CGPA Semester   Department Parental_Education  Dropout
0           1  22.1    Male        25000.0             Yes                 3.36             86.1                      2                 20.4           Yes          No           5.5  0.96          0.90  0.90   Year 1         Arts        High School        0
1           2  20.7    Male        25000.0             Yes                 4.30             68.0                      2                 44.0            No          No           6.8  1.28          1.20  1.19   Year 3  Engineering           Bachelor        1
2           3  22.4    Male        40183.0             Yes                 4.40             70.9                      0                 48.9           Yes          No           5.5  1.68          1.32  1.32   Year 1         Arts             Master        0
3           4  24.4    Male            NaN             Yes                  NaN             82.2                      2                 38.6            No          No           NaN  1.78          1.77  1.77   Year 1           CS        High School        1
4           5  20.5  Female        25319.0             Yes                 4.19             75.7                      1                 23.0            No          No           7.0  1.48          0.91  0.87   Year 4     Business           Bachelor        0

\data analysis

In [45]:
def analyse_dataset(df,target):
    print("=" *60)
    print("DATASET ANALYSIS REPORT")
    print("=" *60)

    #records & columns
    print(f"\nNumber of records(rows) : {df.shape[0]}")
    print(f"Number of columns : {df.shape[1]}")

    #memory usage
    mem_mb = df.memory_usage(deep=True).sum()/(1024 * 1024)
    print(f"Memory usage : {mem_mb:.2f} MB")

    #duplicates
    print(f"Duplicate rows : {df.duplicated().sum()}")

    #data types
    print("\n--- Data Types ---")
    print(df.dtypes)

    #missing values
    print("\n--- Missing Values ---")
    missing = df.isnull().sum()
    missing = missing[missing>0]
    if len(missing)>0:
        for col,cnt in missing.items():
            pct = (cnt / len(df)) *100
            print(f"{col}:{cnt} ({pct:.2f}%)")
    else:
        print("No Missing Values")

    #numeric feature summary
    print("\n--- Numeric Feature Summary ---")
    numeric_cols = df.select_dtypes(include=np.number).columns
    if len(numeric_cols)>0:
        print(df[numeric_cols].describe().round(2).to_string())
    else:
        print("No Numeric Columns")

    #target distribution
    print(f"\n--- Target Distribution: '{target}' ---")
    print(df[target].value_counts())
    print("\npercentage:")
    print((df[target].value_counts(normalize=True) *100).round(2))

    print("=" * 60)

In [46]:
analyse_dataset(placement_df,"PlacementStatus")

============================================================
DATASET ANALYSIS REPORT
============================================================

Number of records(rows) : 10000
Number of columns : 12
Memory usage : 1.04 MB
Duplicate rows : 0

--- Data Types ---
StudentID                      int64
CGPA                         float64
Internships                    int64
Projects                       int64
Workshops/Certifications       int64
AptitudeTestScore              int64
SoftSkillsRating             float64
ExtracurricularActivities        str
PlacementTraining                str
SSC_Marks                      int64
HSC_Marks                      int64
PlacementStatus                  str
dtype: object

--- Missing Values ---
No Missing Values

--- Numeric Feature Summary ---
       StudentID      CGPA  Internships  Projects  Workshops/Certifications  AptitudeTestScore  SoftSkillsRating  SSC_Marks  HSC_Marks
count   10000.00  10000.00     10000.00  10000.00                  10000.00           10000.00          10000.00   10000.00   10000.00
mean     5000.50      7.70         1.05      2.03                      1.01              79.45              4.32      69.16      74.50
std      2886.90      0.64         0.67      0.87                      0.90               8.16              0.41      10.43       8.92
min         1.00      6.50         0.00      0.00                      0.00              60.00              3.00      55.00      57.00
25%      2500.75      7.40         1.00      1.00                      0.00              73.00              4.00      59.00      67.00
50%      5000.50      7.70         1.00      2.00                      1.00              80.00              4.40      70.00      73.00
75%      7500.25      8.20         1.00      3.00                      2.00              87.00              4.70      78.00      83.00
max     10000.00      9.10         2.00      3.00                      3.00              90.00              4.80      90.00      88.00

--- Target Distribution: 'PlacementStatus' ---
PlacementStatus
NotPlaced    5803
Placed       4197
Name: count, dtype: int64
percentage:
PlacementStatus
NotPlaced    58.03
Placed       41.97
Name: proportion, dtype: float64
============================================================

In [47]:
analyse_dataset(course_df,"CourseCompletion")

============================================================
DATASET ANALYSIS REPORT
============================================================

Number of records(rows) : 9000
Number of columns : 9
Memory usage : 0.68 MB
Duplicate rows : 877

--- Data Types ---
UserID                     int64
CourseCategory               str
TimeSpentOnCourse        float64
NumberOfVideosWatched      int64
NumberOfQuizzesTaken       int64
QuizScores               float64
CompletionRate           float64
DeviceType                 int64
CourseCompletion           int64
dtype: object

--- Missing Values ---
No Missing Values

--- Numeric Feature Summary ---
        UserID  TimeSpentOnCourse  NumberOfVideosWatched  NumberOfQuizzesTaken  QuizScores  CompletionRate  DeviceType  CourseCompletion
count  9000.00            9000.00                9000.00               9000.00     9000.00         9000.00      9000.0           9000.00
mean   4498.89              50.16                  10.02                  5.09       74.71           50.34         0.5              0.40
std    2596.85              28.49                   6.03                  3.16       14.38           28.95         0.5              0.49
min       1.00               1.01                   0.00                  0.00       50.01            0.01         0.0              0.00
25%    2251.75              25.44                   5.00                  2.00       62.28           25.65         0.0              0.00
50%    4483.50              49.82                  10.00                  5.00       74.74           50.26         1.0              0.00
75%    6751.25              75.07                  15.00                  8.00       87.02           75.57         1.0              1.00
max    9000.00              99.99                  20.00                 10.00       99.99           99.98         1.0              1.00

--- Target Distribution: 'CourseCompletion' ---
CourseCompletion
0    5432
1    3568
Name: count, dtype: int64
percentage:
CourseCompletion
0    60.36
1    39.64
Name: proportion, dtype: float64
============================================================

In [49]:
analyse_dataset(dropout_df,"Dropout")

============================================================
DATASET ANALYSIS REPORT
============================================================

Number of records(rows) : 10000
Number of columns : 19
Memory usage : 1.76 MB
Duplicate rows : 0

--- Data Types ---
Student_ID                 int64
Age                      float64
Gender                       str
Family_Income            float64
Internet_Access              str
Study_Hours_per_Day      float64
Attendance_Rate          float64
Assignment_Delay_Days      int64
Travel_Time_Minutes      float64
Part_Time_Job                str
Scholarship                  str
Stress_Index             float64
GPA                      float64
Semester_GPA             float64
CGPA                     float64
Semester                     str
Department                   str
Parental_Education           str
Dropout                    int64
dtype: object

--- Missing Values ---
Family_Income:500 (5.00%)
Study_Hours_per_Day:500 (5.00%)
Stress_Index:500 (5.00%)
Parental_Education:511 (5.11%)

--- Numeric Feature Summary ---
       Student_ID       Age  Family_Income  Study_Hours_per_Day  Attendance_Rate  Assignment_Delay_Days  Travel_Time_Minutes  Stress_Index       GPA  Semester_GPA      CGPA   Dropout
count    10000.00  10000.00        9500.00              9500.00         10000.00               10000.00             10000.00       9500.00  10000.00      10000.00  10000.00  10000.00
mean      5000.50     21.03       38377.25                 4.01            81.74                   1.80                30.18          5.51      2.31          2.30      2.30      0.24
std       2886.90      2.14       20496.23                 1.30             8.22                   1.34                11.92          1.77      1.06          1.07      1.07      0.42
min          1.00     17.00       25000.00                 0.50            38.20                   0.00                 5.00          1.00      0.00          0.00      0.00      0.00
25%       2500.75     19.50       25000.00                 3.16            76.40                   1.00                21.90          4.30      1.55          1.52      1.52      0.00
50%       5000.50     21.00       29740.50                 4.00            81.80                   2.00                30.20          5.50      2.35          2.35      2.35      0.00
75%       7500.25     22.50       44520.00                 4.87            87.30                   3.00                38.40          6.70      3.12          3.15      3.15      0.00
max      10000.00     29.60      316601.00                 8.98           100.00                   8.00                74.90         10.00      4.00          4.00      4.00      1.00

--- Target Distribution: 'Dropout' ---
Dropout
0    7646
1    2354
Name: count, dtype: int64
percentage:
Dropout
0    76.46
1    23.54
Name: proportion, dtype: float64
============================================================